import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import * as Resources from '@agnes/resource-control-contracts/schema'
import type { TSchema } from '@sinclair/typebox'
import * as Acp from '../gen/ts/acp.js'
import * as Agnes from '../gen/ts/agnes-v1.js'
import * as App from '../gen/ts/app-server.js'
import * as Packages from '../gen/ts/package-admin.js'
import { METHODS } from '../src/methods.js'
import * as Runtime from '../src/runtime-admin.js'
import * as Schedules from '../src/schedules.js'
import * as Tools from '../src/session-tools.js'

type Node = Record<string, unknown>
/** Flatten TypeBox module scopes and recursive ids into portable document-local JSON pointers. */
export function appServerArtifacts() {
  const definitions: Node = {}
  const modules = [
    ['./acp.js', Acp],
    ['./agnes-v1.js', Agnes],
    ['./package-admin.js', Packages],
    ['@agnes/resource-control-contracts/schema', Resources],
    ['../../src/runtime-admin.js', Runtime],
    ['../../src/schedules.js', Schedules],
    ['../../src/session-tools.js', Tools],
    ['./app-server.js', App],
  ] as const
  const typeNames = new Map<unknown, string>()
  for (const [path, values] of modules)
    for (const [name, schema] of Object.entries(values))
      if (schema && typeof schema === 'object')
        typeNames.set(schema, `Static<typeof import(${JSON.stringify(path)}).${name}>`)
  function portable(schema: unknown, scope: Record<string, string> = {}): unknown {
    if (Array.isArray(schema)) return schema.map((value) => portable(value, scope))
    if (!schema || typeof schema !== 'object') return schema
    const node = schema as Node
    const local = { ...scope }
    if (node.$defs && typeof node.$defs === 'object') {
      const defs = node.$defs as Node
      const prefix = 'D' + createHash('sha256').update(JSON.stringify(defs)).digest('hex').slice(0, 12) + '_'
      for (const key of Object.keys(defs)) {
        local[key] = local[`#/$defs/${key}`] = `#/$defs/${prefix}${key}`
      }
      for (const [key, value] of Object.entries(defs)) {
        const name = prefix + key
        if (!(name in definitions)) {
          definitions[name] = {}
          definitions[name] = portable(value, local)
        }
      }
    }
    if (typeof node.$id === 'string') {
      const name = 'R' + createHash('sha256').update(JSON.stringify(node)).digest('hex').slice(0, 12)
      local[node.$id] = `#/$defs/${name}`
      if (!(name in definitions)) {
        definitions[name] = {}
        definitions[name] = portable(
          Object.fromEntries(Object.entries(node).filter(([key]) => key !== '$id')),
          local,
        )
      }
      return { $ref: `#/$defs/${name}` }
    }
    return Object.fromEntries(
      Object.entries(node)
        .filter(([key]) => key !== '$defs')
        .map(([key, value]) => [
          key,
          key === '$ref' && typeof value === 'string' ? (local[value] ?? value) : portable(value, local),
        ]),
    )
  }
  const catalog: Node = {}
  const typed: string[] = []
  for (const [name, spec] of Object.entries(METHODS)) {
    const key = name.replace(/[^A-Za-z0-9]/g, '_')
    definitions[key + 'Params'] = portable(spec.params)
    if (spec.result) definitions[key + 'Result'] = portable(spec.result)
    catalog[name] = {
      kind: spec.kind,
      direction: spec.direction,
      params: { $ref: `#/$defs/${key}Params` },
      ...(spec.result ? { result: { $ref: `#/$defs/${key}Result` } } : {}),
      ...(spec.administration ? { administration: spec.administration } : {}),
    }
    const type = (schema: TSchema | undefined) => (schema ? (typeNames.get(schema) ?? 'unknown') : 'void')
    if (spec.params && !typeNames.has(spec.params)) throw new Error(`Unnamed params schema: ${name}`)
    if (spec.result && !typeNames.has(spec.result)) throw new Error(`Unnamed result schema: ${name}`)
    typed.push(
      `  ${JSON.stringify(name)}: { params: ${type(spec.params)}; result: ${type(spec.result)}; direction: ${JSON.stringify(spec.direction)}; kind: ${JSON.stringify(spec.kind)} }`,
    )
  }
  definitions.AppServerError = portable(App.AppServerError)
  const schema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://agnes.ai/schema/app-server-v1.json',
    title: 'AGH App Server v1',
    'x-version': 1,
    'x-methods': catalog,
    $defs: definitions,
  }
  const types = `// generated by tools/gen.ts — do not edit\nimport type { Static } from '@sinclair/typebox'\nexport interface AppServerMethods {\n${typed.join('\n')}\n}\nexport type AppServerClientMethod = { [K in keyof AppServerMethods]: AppServerMethods[K]['direction'] extends 'c2s' ? AppServerMethods[K]['kind'] extends 'request' ? K : never : never }[keyof AppServerMethods]\nexport type AppServerParams<M extends keyof AppServerMethods> = AppServerMethods[M]['params']\nexport type AppServerResult<M extends keyof AppServerMethods> = AppServerMethods[M]['result']\n`
  const typeName = (name: string) => name.replace(/[^A-Za-z0-9_$]/g, '_')
  function ts(node: unknown): string {
    if (node === false) return 'never'
    if (!node || typeof node !== 'object') return 'unknown'
    const n = node as Node
    if (typeof n.$ref === 'string') {
      if (!n.$ref.startsWith('#/$defs/')) throw new Error(`Nonlocal schema reference: ${n.$ref}`)
      return typeName(n.$ref.slice(8))
    }
    if ('const' in n) return JSON.stringify(n.const)
    if (Array.isArray(n.enum)) return n.enum.map((x) => JSON.stringify(x)).join(' | ') || 'never'
    for (const [key, separator] of [
      ['anyOf', ' | '],
      ['oneOf', ' | '],
      ['allOf', ' & '],
    ])
      if (Array.isArray(n[key as string]))
        return '(' + (n[key as string] as unknown[]).map(ts).join(separator) + ')'
    if (n.type === 'null') return 'null'
    if (n.type === 'boolean') return 'boolean'
    if (n.type === 'integer' || n.type === 'number') return 'number'
    if (n.type === 'string') return 'string'
    if (n.type === 'array') return `Array<${ts(n.items)}>`
    if (n.type === 'object' || n.properties || n.patternProperties || n.additionalProperties) {
      const required = new Set(Array.isArray(n.required) ? n.required : [])
      const properties = Object.entries((n.properties ?? {}) as Node).map(
        ([name, value]) => `${JSON.stringify(name)}${required.has(name) ? '' : '?'}: ${ts(value)}`,
      )
      if (n.additionalProperties !== false)
        properties.push(
          `[key:string]: ${Object.keys((n.properties ?? {}) as Node).length ? 'unknown' : ts(n.additionalProperties ?? Object.values((n.patternProperties as Node) ?? {})[0])}`,
        )
      return '{ ' + properties.join('; ') + ' }'
    }
    return 'unknown'
  }
  const standalone =
    '// generated by tools/gen.ts — do not edit\n' +
    Object.entries(definitions)
      .map(([name, node]) => `export type ${typeName(name)} = ${ts(node)}`)
      .join('\n') +
    '\nexport interface AppServerMethods {\n' +
    Object.entries(METHODS)
      .map(([name, spec]) => {
        const key = name.replace(/[^A-Za-z0-9]/g, '_')
        return `  ${JSON.stringify(name)}: {params:${key}Params; result:${spec.result ? key + 'Result' : 'void'}; direction:${JSON.stringify(spec.direction)}; kind:${JSON.stringify(spec.kind)}}`
      })
      .join('\n') +
    "\n}\nexport type AppServerParams<M extends keyof AppServerMethods> = AppServerMethods[M]['params']\nexport type AppServerResult<M extends keyof AppServerMethods> = AppServerMethods[M]['result']\n"
  const json = JSON.stringify(schema, null, 2) + '\n'
  return {
    json,
    types,
    standalone,
    standaloneRuntime: `// generated by tools/gen.ts — do not edit\nexport const APP_SERVER_TYPES = ${JSON.stringify(standalone)}\n`,
    runtime: `// generated by tools/gen.ts — do not edit\nexport const APP_SERVER_SCHEMA: Record<string, unknown> = JSON.parse(${JSON.stringify(JSON.stringify(schema))})\n`,
  }
}
export function writeAppServerArtifacts(pkg: string, check: boolean): number {
  const artifacts = appServerArtifacts()
  let dirty = 0
  for (const [path, content] of [
    ['gen/json/app-server-v1.json', artifacts.json],
    ['gen/ts/app-server-methods.ts', artifacts.types],
    ['gen/types/app-server.ts', artifacts.standalone],
    ['gen/ts/app-server-types.ts', artifacts.standaloneRuntime],
    ['gen/ts/app-server-schema.ts', artifacts.runtime],
  ] as const) {
    const file = join(pkg, path)
    if (existsSync(file) && readFileSync(file, 'utf8') === content) continue
    if (check) {
      console.error(`stale: ${path}`)
      dirty++
      continue
    }
    mkdirSync(dirname(file), { recursive: true })
    writeFileSync(file, content)
    console.log(`wrote ${path}`)
  }
  return dirty
}
