import type { SlotKind, SlotScope, SlotSpec } from '@agnes/web-slots'

/**
 * Version of the independent DSH-aligned browser slot contract.
 *
 * This catalog is deliberately separate from the protocol data-slot names and
 * from the set of slots currently mounted by the Agnes shell. A name being
 * known here only means that its contract is understood; the shell must still
 * declare a live owner before a contribution can register into it.
 */
export const DSH_SLOT_CATALOG_VERSION = 'dsh-client-slots/v1' as const

export interface DshSlotDefinition {
  readonly key: string
  readonly kind: SlotKind
  readonly scope: SlotScope
  readonly parent: string | undefined
  readonly public: boolean
  readonly hostOnly: boolean
  readonly owner: string
  readonly fallback: 'host' | 'empty' | 'chain'
}

const definition = (
  key: string,
  kind: SlotKind,
  scope: SlotScope,
  parent: string | undefined,
  owner: string,
  fallback: DshSlotDefinition['fallback'] = kind === 'chain' ? 'chain' : 'empty',
): DshSlotDefinition => ({
  key,
  kind,
  scope,
  parent,
  public: key !== 'root',
  hostOnly: key === 'root',
  owner,
  fallback,
})

/** The 63 keys generated by DSH's client slot catalog, kept in key order. */
export const DSH_SLOT_CATALOG: readonly DshSlotDefinition[] = Object.freeze([
  definition(
    'conversation.approval.detail',
    'single',
    'session',
    'conversation.composer',
    'conversation.composer',
  ),
  definition(
    'conversation.chat.assistant-actions',
    'list',
    'session',
    'conversation.chat.node',
    'conversation.chat.node',
  ),
  definition(
    'conversation.chat.commandview',
    'keyed',
    'session',
    'conversation.chat.node',
    'conversation.chat.node',
  ),
  definition('conversation.chat.node', 'keyed', 'session', 'conversation.view', 'conversation.view'),
  definition(
    'conversation.chat.turnTail',
    'chain',
    'session',
    'conversation.chat.node',
    'conversation.chat.node',
  ),
  definition('conversation.composer', 'chain', 'session', 'main.conversation', 'main.conversation'),
  definition(
    'conversation.composer.bar',
    'single',
    'session-maybe',
    'main.conversation',
    'main.conversation',
  ),
  definition(
    'conversation.composer.dock',
    'list',
    'session',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition('conversation.hero.agentPreset', 'single', 'root', 'main.conversation', 'main.conversation'),
  definition('conversation.hero.brand.mark', 'single', 'root', 'main.conversation', 'main.conversation'),
  definition('conversation.hero.workspace', 'single', 'root', 'main.conversation', 'main.conversation'),
  definition(
    'conversation.hero.workspace.directoryFlow',
    'single',
    'root',
    'conversation.hero.workspace',
    'conversation.hero.workspace',
  ),
  definition(
    'conversation.input.attachments',
    'single',
    'session-maybe',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition('conversation.input.dock', 'list', 'session', 'main.conversation', 'main.conversation'),
  definition(
    'conversation.input.left',
    'list',
    'session',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition(
    'conversation.input.model',
    'single',
    'session',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition(
    'conversation.input.overlay',
    'list',
    'session',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition(
    'conversation.input.permission',
    'single',
    'session',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition(
    'conversation.input.plan',
    'single',
    'session',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition(
    'conversation.input.right',
    'list',
    'session',
    'conversation.composer.bar',
    'conversation.composer.bar',
  ),
  definition('conversation.message.images', 'single', 'session', 'conversation.view', 'conversation.view'),
  definition('conversation.session', 'single', 'session', 'main.conversation', 'main.conversation'),
  definition('conversation.session.header', 'single', 'session', 'main.conversation', 'main.conversation'),
  definition(
    'conversation.session.header.actions',
    'list',
    'session',
    'conversation.session.header',
    'conversation.session.header',
  ),
  definition(
    'conversation.session.header.corner',
    'single',
    'session',
    'conversation.session.header',
    'conversation.session.header',
  ),
  definition(
    'conversation.session.header.lineage',
    'single',
    'session',
    'conversation.session.header',
    'conversation.session.header',
  ),
  definition(
    'conversation.session.header.utilities',
    'list',
    'session',
    'conversation.session.header',
    'conversation.session.header',
  ),
  definition('conversation.trajectory.images', 'single', 'session', 'conversation.view', 'conversation.view'),
  definition('conversation.view', 'list', 'session', 'conversation.session', 'conversation.session'),
  definition('main', 'keyed', 'root', 'root', 'root'),
  definition('main.conversation', 'single', 'session-maybe', 'main', 'main'),
  definition('rightbar', 'single', 'root', 'root', 'root'),
  definition('rightbar.session', 'single', 'session', 'rightbar', 'rightbar'),
  definition('root', 'single', 'root', undefined, 'runtime', 'host'),
  definition('settings.action', 'list', 'root', 'sidebar.settings', 'sidebar.settings'),
  definition('settings.close', 'single', 'root', 'sidebar.settings', 'sidebar.settings'),
  definition('settings.general.item', 'list', 'root', 'settings.section', 'settings.section'),
  definition('settings.header', 'single', 'root', 'sidebar.settings', 'sidebar.settings'),
  definition('settings.models.footer', 'list', 'root', 'settings.section', 'settings.section'),
  definition('settings.models.provider-card', 'keyed', 'root', 'settings.section', 'settings.section'),
  definition('settings.onboarding', 'list', 'root', 'sidebar.settings', 'sidebar.settings'),
  definition('settings.plugin.item', 'keyed', 'root', 'settings.plugins.tab', 'settings.plugins.tab'),
  definition('settings.plugins.tab', 'list', 'root', 'settings.section', 'settings.section'),
  definition('settings.section', 'list', 'root', 'sidebar.settings', 'sidebar.settings'),
  definition('settings.trigger', 'single', 'root', 'sidebar.settings', 'sidebar.settings'),
  definition('shell.overlay', 'list', 'root', 'root', 'root'),
  definition('sidebar', 'single', 'root', 'root', 'root'),
  definition('sidebar.brand.mark', 'single', 'root', 'sidebar', 'sidebar'),
  definition('sidebar.brand.name', 'single', 'root', 'sidebar', 'sidebar'),
  definition('sidebar.footer.action', 'list', 'root', 'sidebar', 'sidebar'),
  definition('sidebar.panellist', 'list', 'root', 'sidebar', 'sidebar'),
  definition('sidebar.right.pane.tab', 'keyed', 'session', 'rightbar.session', 'rightbar.session'),
  definition('sidebar.right.pane.tab.title', 'keyed', 'session', 'rightbar.session', 'rightbar.session'),
  definition(
    'sidebar.right.tab.document',
    'keyed',
    'session',
    'sidebar.right.pane.tab',
    'sidebar.right.pane.tab',
  ),
  definition(
    'sidebar.right.tab.guide',
    'chain',
    'session',
    'sidebar.right.pane.tab',
    'sidebar.right.pane.tab',
  ),
  definition(
    'sidebar.right.tab.guide.entry',
    'keyed',
    'session',
    'sidebar.right.pane.tab',
    'sidebar.right.pane.tab',
  ),
  definition('sidebar.right.tab.menu.item', 'list', 'session', 'rightbar.session', 'rightbar.session'),
  definition('sidebar.settings', 'single', 'root', 'sidebar', 'sidebar'),
  definition('sidebar.workspaces', 'single', 'root', 'sidebar', 'sidebar'),
  definition(
    'sidebar.workspaces.directoryFlow',
    'single',
    'root',
    'sidebar.workspaces',
    'sidebar.workspaces',
  ),
  definition('tool.call.images', 'single', 'session', 'tool.call.toolview', 'tool.call.toolview'),
  definition('tool.call.toolview', 'keyed', 'session', 'conversation.chat.node', 'conversation.chat.node'),
  definition('tool.view.cordis', 'keyed', 'session', 'tool.call.toolview', 'tool.call.toolview'),
])

export type DshSlotName = (typeof DSH_SLOT_CATALOG)[number]['key']

export const DSH_SLOT_NAMES: readonly DshSlotName[] = Object.freeze(
  DSH_SLOT_CATALOG.map((slot) => slot.key) as DshSlotName[],
)

export const DSH_PUBLIC_SLOT_NAMES: readonly DshSlotName[] = Object.freeze(
  DSH_SLOT_CATALOG.filter((slot) => slot.public).map((slot) => slot.key) as DshSlotName[],
)

/**
 * Slots that the current Agnes shell actually declares. New catalog entries
 * remain blocked until a corresponding host row is mounted.
 */
export const DSH_RUNTIME_SUPPORTED_SLOT_NAMES: readonly string[] = Object.freeze([
  'conversation.approval.detail',
  'conversation.chat.assistant-actions',
  'conversation.chat.node',
  'conversation.chat.commandview',
  'conversation.chat.turnTail',
  'conversation.composer.dock',
  'conversation.composer',
  'conversation.composer.bar',
  'conversation.hero.agentPreset',
  'conversation.hero.brand.mark',
  'conversation.hero.workspace',
  'conversation.hero.workspace.directoryFlow',
  'conversation.input.attachments',
  'conversation.input.dock',
  'conversation.input.left',
  'conversation.input.model',
  'conversation.input.overlay',
  'conversation.input.permission',
  'conversation.input.plan',
  'conversation.input.right',
  'conversation.session',
  'conversation.session.header',
  'conversation.session.header.actions',
  'conversation.session.header.corner',
  'conversation.session.header.lineage',
  'conversation.session.header.utilities',
  'conversation.view',
  'conversation.message.images',
  'conversation.trajectory.images',
  'settings.action',
  'settings.close',
  'settings.general.item',
  'settings.header',
  'settings.models.footer',
  'settings.models.provider-card',
  'settings.onboarding',
  'settings.plugin.item',
  'settings.plugins.tab',
  'settings.section',
  'settings.trigger',
  'rightbar',
  'rightbar.session',
  'sidebar.right.pane.tab',
  'sidebar.right.pane.tab.title',
  'sidebar.right.tab.document',
  'sidebar.right.tab.guide',
  'sidebar.right.tab.guide.entry',
  'sidebar.right.tab.menu.item',
  'sidebar',
  'sidebar.brand.mark',
  'sidebar.brand.name',
  'sidebar.footer.action',
  'sidebar.panellist',
  'sidebar.settings',
  'sidebar.workspaces',
  'sidebar.workspaces.directoryFlow',
  'main',
  'main.conversation',
  'shell.overlay',
  'tool.call.toolview',
  'tool.call.images',
  'tool.view.cordis',
])

const catalogByName = new Map(DSH_SLOT_CATALOG.map((slot) => [slot.key, slot]))

export function getDshSlotDefinition(name: string): DshSlotDefinition | undefined {
  return catalogByName.get(name)
}

export function isKnownDshSlot(name: string): name is DshSlotName {
  return catalogByName.has(name)
}

export function isPublicDshSlot(name: string): name is DshSlotName {
  return catalogByName.get(name)?.public === true
}

export function isRuntimeSupportedDshSlot(name: string): boolean {
  return DSH_RUNTIME_SUPPORTED_SLOT_NAMES.includes(name)
}

export function dshSlotSpec(name: string): SlotSpec | undefined {
  const slot = catalogByName.get(name)
  return slot === undefined ? undefined : { kind: slot.kind, scope: slot.scope }
}

export const DSH_SLOT_COUNTS = Object.freeze({
  total: DSH_SLOT_CATALOG.length,
  public: DSH_PUBLIC_SLOT_NAMES.length,
  hostOnly: DSH_SLOT_CATALOG.filter((slot) => slot.hostOnly).length,
  single: DSH_SLOT_CATALOG.filter((slot) => slot.kind === 'single').length,
  list: DSH_SLOT_CATALOG.filter((slot) => slot.kind === 'list').length,
  keyed: DSH_SLOT_CATALOG.filter((slot) => slot.kind === 'keyed').length,
  chain: DSH_SLOT_CATALOG.filter((slot) => slot.kind === 'chain').length,
  root: DSH_SLOT_CATALOG.filter((slot) => slot.scope === 'root').length,
  session: DSH_SLOT_CATALOG.filter((slot) => slot.scope === 'session').length,
  sessionMaybe: DSH_SLOT_CATALOG.filter((slot) => slot.scope === 'session-maybe').length,
})
