import { readFileSync } from 'node:fs'
import { HOOK_TABLE } from '../src/generated/hook-table.js'
import { SLOT_TABLE } from '../src/generated/slot-table.js'
import { HOOK_EVENTS, type HookEvent, type HookSpec } from '../src/hooks.js'
import { SLOT_NAMES, type SlotName, type SlotSpec } from '../src/slots.js'
import { TOOL_META_KEYS } from '../src/tool.js'

const header = (source: string) =>
  `<!-- generated by tools/gen-docs.ts from protocol ${source} — do not edit -->\n\n`
const cell = (text: string) =>
  text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('|', '&#124;')
    .replaceAll('\r\n', '\n')
    .replaceAll('\n', '<br>')
export function renderHooksDoc(input: {
  table: Record<HookEvent, HookSpec>
  descriptions: Record<HookEvent, { payload: string; ret: string }>
}): string {
  const rows = HOOK_EVENTS.map((name) => {
    const row = input.table[name],
      description = input.descriptions[name]
    return `| \`${name}\` | ${row.mode} | ${row.category} | ${row.failPolicy} | ${row.timeoutMs} | ${row.replayOnResume ? '✓' : '–'} | ${cell(description.payload)} | ${cell(description.ret)} |`
  })
  return `${header('hooks.json')}# Hook events\n\nPayload and return summaries describe the wire schema. Local author callbacks also carry HookContext/getSurface; observe handlers return void and require normalization to wire null. Author types and the normalization boundary are documented in [the hook authoring types](../src/hooks.ts).\n\n| Event | Mode | Category | Failure | Timeout ms | Replay | Payload | Return |\n|---|---|---|---|---|---|---|---|\n${rows.join('\n')}\n`
}
export function renderSlotsDoc(input: {
  table: Record<SlotName, SlotSpec>
  payloadDescriptions: Record<SlotName, string>
}): string {
  const rows = SLOT_NAMES.map((name) => {
    const row = input.table[name]
    return `| \`${name}\` | ${row.cardinality} | ${row.order} | ${row.surfaces.join(', ')} | ${row.failPolicy} | ${cell(input.payloadDescriptions[name])} |`
  })
  return `${header('slots.json')}# UI slots\n\nPayloads must pass their schema and the 64 KiB JSON byte limit. Null from an author fill means no content. Runtime capabilities and trigger scheduling remain host responsibilities.\n\n| Slot | Cardinality | Order | Surfaces | Failure | Payload |\n|---|---|---|---|---|---|\n${rows.join('\n')}\n`
}
export function renderToolsMetaDoc(input: {
  keys: readonly string[]
  descriptions: Record<string, string>
}): string {
  const rows = input.keys.map((key) => {
    const description = input.descriptions[key]
    if (!description) throw new Error(`missing tool metadata description: ${key}`)
    return `| \`${key}\` | ${cell(description)} |`
  })
  return `${header('tooldef.json')}# Tool metadata\n\nAll eight keys must be explicitly present. Authors may explicitly set costHint, deferLoading and requiresApproval to undefined; wire metadata normalizes these to null. A missing key is E_TOOLDEF_META.\n\n| Key | Meaning |\n|---|---|\n${rows.join('\n')}\n`
}
type Schema = {
  description?: string
  type?: string | string[]
  required?: string[]
  properties?: Record<string, Schema>
  enum?: unknown[]
  oneOf?: unknown[]
  anyOf?: unknown[]
  $ref?: string
}
type Document = {
  $defs: Record<string, Schema>
  'x-agnes-hook-io'?: Record<string, [string, string]>
  'x-agnes-slot-table'?: Record<string, { payload: string }>
}
const read = (name: string): Document =>
  JSON.parse(readFileSync(new URL(`../../protocol/schema/${name}`, import.meta.url), 'utf8'))
export function schemaSummary(doc: Document, file: string, name: string): string {
  const schema = doc.$defs[name]
  if (!schema) throw new Error(`missing definition ${file}#${name}`)
  const required = schema.required ?? [],
    optional = Object.keys(schema.properties ?? {}).filter((key) => !required.includes(key))
  const text =
    schema.description ||
    [
      schema.type ? `type: ${String(schema.type)}` : '',
      schema.$ref ? `reference: ${schema.$ref}` : '',
      required.length ? `required: ${required.join(', ')}` : '',
      optional.length ? `optional: ${optional.join(', ')}` : '',
      schema.enum ? `enum: ${schema.enum.join(', ')}` : '',
      schema.oneOf ? `oneOf: ${schema.oneOf.length} branches` : '',
      schema.anyOf ? `anyOf: ${schema.anyOf.length} branches` : '',
    ]
      .filter(Boolean)
      .join('; ')
  if (!text) throw new Error(`no summary for ${name}`)
  return `[${name}](../../protocol/schema/${file}#/$defs/${name}): ${text}`
}
export function generateAll(): Record<string, string> {
  const hooks = read('hooks.json'),
    slots = read('slots.json'),
    tools = read('tooldef.json')
  const descriptions = Object.fromEntries(
    HOOK_EVENTS.map((name) => {
      const io = hooks['x-agnes-hook-io']?.[name]
      if (!io) throw new Error(`missing hook mapping ${name}`)
      return [
        name,
        {
          payload: schemaSummary(hooks, 'hooks.json', io[0]),
          ret: schemaSummary(hooks, 'hooks.json', io[1]),
        },
      ]
    }),
  ) as Record<HookEvent, { payload: string; ret: string }>
  const payloadDescriptions = Object.fromEntries(
    SLOT_NAMES.map((name) => {
      const mapping = slots['x-agnes-slot-table']?.[name]
      if (!mapping) throw new Error(`missing slot mapping ${name}`)
      return [name, schemaSummary(slots, 'slots.json', mapping.payload)]
    }),
  ) as Record<SlotName, string>
  const descriptionsMeta = Object.fromEntries(
    TOOL_META_KEYS.map((key) => [key, tools.$defs.ToolMeta?.properties?.[key]?.description ?? '']),
  )
  return {
    'services.md': `${header('extension-service.json')}# Extension Services

${schemaSummary(read('extension-service.json'), 'extension-service.json', 'ServiceCapability')}

Register a declared name with registerService and a Promise-returning handler. Schemas are plain JSON data objects; Host compiles them. checkServiceDef validates metadata only and never executes the handler. Actor, source and requestId come from Host. Effect identity, grants, lease, timeout and result limits require Host/daemon wiring. Service has no session/model/UI access.
`,
    'projections.md': `${header('projection.json')}# Extension Projections

${schemaSummary(read('projection.json'), 'projection.json', 'ProjectionCapability')}

registerProjection accepts name, positive stateVersion, plain JSON stateSchema and synchronous init/apply/view functions. Handlers receive no context and must not perform I/O. Host filters exact declared event types, validates state/view and owns quarantine and cleanup. Host injects ProjectionReader.readOwn(name) into Tool, Hook and Slot callbacks for the current extension and session. It rechecks lease after scanning and before folding. Saved readers are unavailable outside their owner invocation. Core callbacks without extension authority use unavailableProjections. Reload and package removal acceptance remain separate lifecycle tasks.
`,
    'hooks.md': renderHooksDoc({ table: HOOK_TABLE, descriptions }),
    'slots.md': renderSlotsDoc({ table: SLOT_TABLE, payloadDescriptions }),
    'tools-meta.md': renderToolsMetaDoc({ keys: TOOL_META_KEYS, descriptions: descriptionsMeta }),
  }
}
