import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'

const templatesRoot = new URL('../../../../templates/', import.meta.url)
const scaffold = await readFile(new URL('create-agh-plugin.mjs', templatesRoot), 'utf8')
const templateNames = ['tool', 'tool-with-panel', 'mcp-skills', 'model-adapter', 'loop']
const files = {}
async function collect(url, prefix) {
  for (const entry of await readdir(url, { withFileTypes: true })) {
    const path = `${prefix}/${entry.name}`
    if (entry.isDirectory()) await collect(new URL(`${entry.name}/`, url), path)
    else files[path] = await readFile(new URL(entry.name, url), 'utf8')
  }
}
for (const name of templateNames) await collect(new URL(`${name}/`, templatesRoot), name)
const scaffoldSource = scaffold
  .slice(scaffold.indexOf('export async function scaffold'), scaffold.indexOf('\nif (process.argv[1]'))
  .replace('export async function', 'async function')
const skill = await readFile(new URL('skills/plugin-creator/SKILL.md', import.meta.url), 'utf8')
const data = { templateNames, files, scaffoldSource, skill }
const output = `// Generated by gen-assets.mjs from create-agh-plugin, templates and the bundled Skill.\n// biome-ignore-all lint/suspicious/noTemplateCurlyInString: canonical template source contains literal placeholders
// biome-ignore format: preserve the generator output\nexport const creatorAssets = ${JSON.stringify(data, null, 2)} as const\n`
await mkdir(new URL('src/generated/', import.meta.url), { recursive: true })
const target = new URL('src/generated/assets.ts', import.meta.url)
if (process.argv.includes('--check')) {
  if ((await readFile(target, 'utf8')) !== output)
    throw new Error('Plugin creator assets are stale; run gen-assets.mjs')
} else await writeFile(target, output)
