import type { ComponentProps } from '@ant-design/x-markdown'
import { createContext, Fragment, type MutableRefObject, useContext, useLayoutEffect, useRef } from 'react'
import { escapeMarkdownHtml } from './markdown-policy.js'
import { interactionInside } from './markdown-snapshot.js'

type Range = { start: number; end: number; at: number; id: number }
export type RevealPlan = { source: string; value: string | undefined; ranges: Range[]; serial: number }
export const MarkdownRevealOwner = createContext<
  | {
      source: string
      committed: MutableRefObject<RevealPlan | undefined>
    }
  | undefined
>(undefined)

/** Publish only the plan whose real React tree has committed, never a speculative render. */
export function RevealRoot({ domNode, children }: ComponentProps) {
  const owner = useContext(MarkdownRevealOwner)
  const raw = (domNode as { attribs: Record<string, string> }).attribs['data-agnes-plan']
  useLayoutEffect(() => {
    if (owner && raw) owner.committed.current = { ...JSON.parse(raw), source: owner.source }
  }, [owner, raw])
  return <>{children}</>
}

function encodeData(value: unknown): string {
  return JSON.stringify(value).replaceAll('<', '\\u003c').replaceAll('>', '\\u003e')
}

type Piece = { text: string; start: number; id?: number; delay?: number }
const DURATION = 480
const MAX_TEXT = 65_536
const MAX_VISITS = 4_096
const MAX_RANGES = 32
const MAX_FRAGMENTS = 128
const EXCLUDED = 'button,input,select,textarea,.code-toolbar,script,style,[hidden],[aria-hidden="true"]'

function splitsPair(value: string, offset: number): boolean {
  const before = value.charCodeAt(offset - 1)
  const after = value.charCodeAt(offset)
  return before >= 0xd800 && before <= 0xdbff && after >= 0xdc00 && after <= 0xdfff
}

/** Plan only detached parser output. Attached DOM belongs exclusively to XMarkdown/React. */
export function planMarkdownReveal(
  html: string,
  source: string,
  streaming: boolean,
  host: HTMLElement | null,
  previous: RevealPlan | undefined,
): string {
  const parsed = new DOMParser().parseFromString(html, 'text/html')
  // Escaped literals are generated by our policy, never accepted as raw user HTML.
  for (const span of parsed.querySelectorAll('[data-agnes-literal]'))
    span.textContent = span.getAttribute('data-agnes-literal') ?? ''
  const segments: Array<{ node: Text; start: number; end: number }> = []
  const values: string[] = []
  let length = 0
  let visited = 0
  const walker = parsed.createTreeWalker(parsed.body, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT)
  let valid = true
  for (let node = walker.nextNode(); node; node = walker.nextNode()) {
    if (++visited > MAX_VISITS) {
      valid = false
      break
    }
    if (node.nodeType !== Node.TEXT_NODE) continue
    const text = node as Text
    const parent = text.parentElement
    if (parent?.closest(EXCLUDED) || !text.length || (parent === parsed.body && !text.data.trim())) continue
    const end = length + text.length
    if (end > MAX_TEXT) {
      valid = false
      break
    }
    segments.push({ node: text, start: length, end })
    values.push(text.data)
    length = end
  }
  const value = values.join('')
  const view = host?.ownerDocument.defaultView
  const visible = Boolean(
    host?.isConnected &&
      !host.closest('[hidden],[aria-hidden="true"],details:not([open])') &&
      host.ownerDocument.visibilityState !== 'hidden',
  )
  const allowed =
    valid &&
    streaming &&
    visible &&
    !interactionInside(host) &&
    view &&
    typeof view.matchMedia === 'function' &&
    !view.matchMedia('(prefers-reduced-motion: reduce)').matches
  const now = view?.performance.now() ?? 0
  let serial = previous?.serial ?? 0
  let ranges: Range[] = []
  if (
    allowed &&
    previous?.value !== undefined &&
    source.startsWith(previous.source) &&
    value.startsWith(previous.value) &&
    !splitsPair(value, previous.value.length)
  ) {
    ranges = previous.ranges.filter((range) => now - range.at < DURATION)
    if (value.length > previous.value.length)
      ranges.push({ start: previous.value.length, end: value.length, at: now, id: ++serial })
    ranges = ranges.slice(-MAX_RANGES)
  }
  const plans: Array<{ node: Text; pieces: Piece[] }> = []
  let fragments = 0
  for (const segment of segments) {
    const pieces: Piece[] = []
    let cursor = 0
    for (const range of ranges) {
      const start = Math.max(range.start, segment.start) - segment.start
      const end = Math.min(range.end, segment.end) - segment.start
      if (start >= end) continue
      if (
        ++fragments > MAX_FRAGMENTS ||
        splitsPair(segment.node.data, start) ||
        splitsPair(segment.node.data, end)
      )
        valid = false
      if (start > cursor) pieces.push({ text: segment.node.data.slice(cursor, start), start: cursor })
      pieces.push({
        text: segment.node.data.slice(start, end),
        start,
        id: range.id,
        delay: -Math.max(0, now - range.at),
      })
      cursor = end
    }
    if (cursor < segment.node.length) pieces.push({ text: segment.node.data.slice(cursor), start: cursor })
    plans.push({ node: segment.node, pieces })
  }
  if (!valid) ranges = []
  // Always use the same React leaf shape, even for the first unanimated snapshot.
  for (const [index, { node, pieces }] of plans.entries()) {
    const span = parsed.createElement('span')
    span.setAttribute('key', `agnes-text-${index}`)
    span.setAttribute('data-agnes-pieces', encodeData(valid ? pieces : [{ text: node.data, start: 0 }]))
    node.replaceWith(span)
  }
  const data = { value: valid ? value : undefined, ranges, serial }
  return `<agnes-reveal-root data-agnes-plan="${escapeMarkdownHtml(encodeData(data))}">${parsed.body.innerHTML}</agnes-reveal-root>`
}

/** Each fragment keeps its own first delay; a reused node's animation never restarts. */
export function RevealText({ domNode, children }: ComponentProps) {
  const attribs = (domNode as { attribs?: Record<string, string> }).attribs
  const raw = attribs?.['data-agnes-pieces']
  const delays = useRef(new Map<number, number>())
  if (raw === undefined) {
    const literal = attribs?.['data-agnes-literal']
    return literal === undefined ? <span>{children}</span> : children
  }
  const pieces = JSON.parse(raw) as Piece[]
  const active = new Set(pieces.flatMap((piece) => (piece.id === undefined ? [] : [piece.id])))
  for (const id of delays.current.keys()) if (!active.has(id)) delays.current.delete(id)
  return (
    <>
      {pieces.map((piece) => {
        if (piece.id === undefined) return <Fragment key={`plain-${piece.start}`}>{piece.text}</Fragment>
        if (!delays.current.has(piece.id)) delays.current.set(piece.id, piece.delay ?? 0)
        return (
          <span
            key={piece.id}
            className="message-reveal-fragment"
            style={{
              animationDuration: `${DURATION}ms`,
              animationDelay: `${delays.current.get(piece.id)}ms`,
            }}
          >
            {piece.text}
          </span>
        )
      })}
    </>
  )
}
