import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { renderCoverage, syncGeneratedFile } from '../generate/coverage.js'
import { loadHooksMap } from '../src/index.js'

const temporaryDirectories: string[] = []
afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) rmSync(directory, { recursive: true })
})

describe('COVERAGE.md', () => {
  const rendered = renderCoverage(loadHooksMap(), '0.0.0')

  it('has 27 rows, the stable mapping count, and every explicit unsupported field', () => {
    expect(rendered.match(/^\| `[A-Za-z]+` \|/gm)).toHaveLength(27)
    expect(rendered).toContain('mapped 12 / 27')
    for (const field of ['updatedInput', 'updatedPermissions', 'transcript_path'])
      expect(rendered).toContain(`\`${field}\``)
  })

  it('matches the checked-in generated document', () => {
    expect(readFileSync(new URL('../COVERAGE.md', import.meta.url), 'utf8')).toBe(rendered)
  })

  it('fails closed in check mode when one generated byte drifts and does not rewrite it', () => {
    const directory = mkdtempSync(join(tmpdir(), 'agnes-bridges-coverage-'))
    temporaryDirectories.push(directory)
    const path = join(directory, 'COVERAGE.md')
    writeFileSync(path, `${rendered}drift`)
    expect(syncGeneratedFile({ check: true, path, content: rendered })).toBe(false)
    expect(readFileSync(path, 'utf8')).toBe(`${rendered}drift`)
  })
})
